linters-settings:
  bannedfunc:
    - (fmt).Println: 'Disable fmt.Println'
    - (fmt).Printf: 'Disable fmt.Printf'
    - (github.com/stretchr/testify/require).*: 'Disable github.com/stretchr/testify/require.*'

linters:
  enable:
    - bannedfunc
